# Generated by Django 3.1.6 on 2021-05-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('CODE', models.CharField(max_length=512)),
                ('NAME', models.CharField(max_length=512)),
            ],
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры',},
        ),
        migrations.CreateModel(
            name='PropertyValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IBLOCK_ELEMENT_ID', models.IntegerField(unique=True)),
                ('PROPERTY_276', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_429', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_326', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_574', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_265', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_284', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_541', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_542', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_343', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_428', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_274', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_263', models.FloatField(blank=True, null=True)),
                ('PROPERTY_264', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_594', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_344', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_483', models.FloatField(blank=True, max_length=512, null=True)),
                ('PROPERTY_536', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_540', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_356', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_567', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_332', models.CharField(blank=True, max_length=512, null=True)),
                ('PROPERTY_283', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={'verbose_name': 'Значения параметра', 'verbose_name_plural': 'Значения параметров',},
        ),
        migrations.CreateModel(
            name='PropertyMultipleValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IBLOCK_ELEMENT_ID', models.IntegerField()),
                ('IBLOCK_PROPERTY_ID', models.CharField(max_length=512)),
                ('VALUE', models.CharField(blank=True, max_length=512, null=True)),
                ('VALUE_ENUM', models.CharField(blank=True, max_length=512, null=True)),
                ('VALUE_NUM', models.FloatField(blank=True, null=True)),
                ('DESCRIPTION', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Параметр с несколькими значениями',
                'verbose_name_plural': 'Параметры с несколькими значениями',
                'unique_together': {('IBLOCK_ELEMENT_ID', 'IBLOCK_PROPERTY_ID', 'VALUE')},
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('NAME', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препарат',
                'unique_together': {('ID', 'NAME')},
            },
        ),
        migrations.CreateModel(
            name='ProductMNN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MNN_ID', models.CharField(max_length=512)),
                ('PRODUCT_ID', models.IntegerField(blank=True, null=True)),
                ('MNN_NAME', models.CharField(blank=True, max_length=512, null=True, verbose_name='Наименование')),
                ('MNN_CODE', models.CharField(blank=True, max_length=512, null=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Международное непатентованное наименование',
                'verbose_name_plural': 'Международное непатентованное наименование',
                'unique_together': {('MNN_ID', 'PRODUCT_ID')},
            },
        ),
    ]
