# Generated by Django 3.1.6 on 2021-05-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('ORDER_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_ID', models.CharField(max_length=200)),
                ('DETAIL_PAGE_URL', models.CharField(max_length=200)),
            ],
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины',},
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS_ID', models.CharField(max_length=1)),
                ('LID', models.CharField(max_length=200)),
            ],
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы',},
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=200)),
            ],
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары',},
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('CODE', models.CharField(max_length=200)),
                ('NAME', models.CharField(max_length=200)),
            ],
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры',},
        ),
        migrations.CreateModel(
            name='PropertyMultipleValues',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('IBLOCK_ELEMENT_ID', models.IntegerField()),
                ('IBLOCK_PROPERTY_ID', models.IntegerField()),
                ('VALUE', models.IntegerField()),
                ('VALUE_ENUM', models.CharField(max_length=200)),
                ('DESCRIPTION', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Параметр с несколькими значениями',
                'verbose_name_plural': 'Параметры с несколькими значениями',
            },
        ),
        migrations.CreateModel(
            name='PropertyValues',
            fields=[
                ('IBLOCK_ELEMENT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('PROPERTY_276', models.CharField(max_length=200)),
                ('PROPERTY_429', models.CharField(max_length=200)),
                ('PROPERTY_326', models.CharField(max_length=200)),
                ('PROPERTY_574', models.CharField(max_length=200)),
                ('PROPERTY_265', models.CharField(max_length=200)),
                ('PROPERTY_284', models.CharField(max_length=200)),
                ('PROPERTY_541', models.CharField(max_length=200)),
                ('PROPERTY_542', models.CharField(max_length=200)),
                ('PROPERTY_343', models.CharField(max_length=200)),
                ('PROPERTY_428', models.CharField(max_length=200)),
                ('PROPERTY_274', models.CharField(max_length=200)),
                ('PROPERTY_263', models.CharField(max_length=200)),
                ('PROPERTY_264', models.CharField(max_length=200)),
                ('PROPERTY_594', models.CharField(max_length=200)),
                ('PROPERTY_344', models.CharField(max_length=200)),
                ('PROPERTY_483', models.CharField(max_length=200)),
                ('PROPERTY_536', models.CharField(max_length=200)),
                ('PROPERTY_540', models.CharField(max_length=200)),
                ('PROPERTY_356', models.CharField(max_length=200)),
                ('PROPERTY_567', models.CharField(max_length=200)),
                ('PROPERTY_332', models.CharField(max_length=200)),
                ('PROPERTY_283', models.CharField(max_length=200)),
            ],
            options={'verbose_name': 'Значения параметра', 'verbose_name_plural': 'Значения параметров',},
        ),
    ]
