# Generated by Django 3.1.6 on 2021-05-29 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaptekahack', '0002_auto_20210529_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventForReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_datetime', models.DateTimeField(verbose_name='Дата и время события')),
                (
                    'event_code',
                    models.CharField(
                        choices=[('taking_medical_drugs', 'Прием препарата')],
                        db_index=True,
                        max_length=50,
                        verbose_name='Инициализирующее событие',
                    ),
                ),
                ('is_success', models.BooleanField(default=False, verbose_name='Событие успешно?')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                (
                    'course',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reminder',
                        to='eaptekahack.treatmentcourse',
                        verbose_name='Курс',
                    ),
                ),
            ],
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События',},
        ),
        migrations.DeleteModel(name='MedicationReminder',),
    ]
